# Generated by Django 3.1.5 on 2024-09-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('author_name', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=32)),
                ('product_type', models.CharField(max_length=32)),
            ],
        ),
    ]
