"""empty message

Revision ID: 31d084b0bb3d
Revises: a4751a1cd589
Create Date: 2024-09-15 12:35:30.111666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31d084b0bb3d'
down_revision = 'a4751a1cd589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': None}
    )
    op.drop_table('product_copies')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_copy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_copy', ['product_copy_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platformType', sa.String(length=32), nullable=True))
        batch_op.drop_column('datatype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datatype', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('platformType')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_copy_id')

    op.create_table('product_copies',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_copies_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='product_copies_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('product_copy')
    # ### end Alembic commands ###
